### PR TITLE
Tweak build, and extend API

### PR DESCRIPTION
**Pull request by alexarchambault**
This PR
- adds a `AsDisplayData` interface that users can add to their classes, so that they are displayed as display data straightaway, without needing registration,
- adds an override of `Registration.find` allowing one to specify a default displayer if no specific one is found (I intend to pass `null` here, to know if a class actually has a displayer or not - not sure it's fine to pass `null` to `Registration.setDefault`), and
- tweaks a bit the build (add gradle wrapper and `.gitignore`).

### CODE REVIEW

**Comment by alexarchambault** [comment]
ping @rgbkrk @rdblue

**Comment by rdblue** [comment]
@alexarchambault, I think these changes should be split into different pull requests. The build changes aren't related to the others, and the default change is unrelated to the `AsDisplayData` change.

Also, I'd like for those pull requests to have bit more information about why the change is necessary compared to how this works today. What is display data? Why is the current default handling insufficient?  What are the build tweaks? I would expect those questions to be answered along with the submission.

**Comment by rgbkrk** [comment]
I'm assuming the `AsDisplayData` is intended to be used like IPython's `display` call? Might be good to show the usage in the README (unless there are other good doc forms for this).

**Comment by alexarchambault** [comment]
Superseded by https://github.com/jupyter/jvm-repr/pull/16, https://github.com/jupyter/jvm-repr/pull/17, https://github.com/jupyter/jvm-repr/pull/18, https://github.com/jupyter/jvm-repr/pull/19.

**Pull request closed without merging**
