### PR TITLE
Add support for interfaces.

### LINKED ISSUE #8: Registering displayers for interfaces doesn't work
The implementation of `Registration.find()` walks the superclass chain looking for a matching displayer.  This means that registering a displayer for an interface has no effect (the registration will succeed, but the displayer will never be found).

There would need to be some way to resolve the ambiguity if matches were found for both a class and an interface or for two interfaces.

### PR DESCRIPTION
**Pull request by rdblue**
This fixes #8.

### CODE REVIEW

**Comment by rdblue** [comment]
@jpallas, can you review this?

**Comment by jpallas** [comment]
A problem with this implementation is that it won't find a displayer for an indirect interface.  That is, if I have something like this:

```java
interface Customizable {
    String getRepresentation();
};

interface Pet extends Customizable {
    String getName();
};

class Dog implements Pet { ... };
```

and I register a displayer for `Customizable`, displaying a `Dog` won't find that displayer.

The example is a little contrived, but cases like this definitely happen in the collection hierarchies of Java and Scala (and probably others) where it would be reasonable to want a displayer for such an interface.

**Comment by rdblue** [comment]
@jpallas, I updated this to use a breadth-first search of interfaces and superclasses, then added a test for the case you caught.

**Comment by jpallas** [comment]
Looks good to me.  The only change I'd suggest is to update the Javadoc.  
* `Displayer::display` says "objects of type T or subclasses of T", "subclasses" should probably be "subtypes"
* `Displayers::register` says "for a class", "class" could be "class/interface"
* `Registration::add` says "Registers a Displayer instance for a class", suggest adding "or interface"
* `Registration::find` says 
   > A displayer is found by checking registrations for the given class and its superclasses.

   I don't know whether it's appropriate to mention the breadth-first search behavior in the doc, but it could say something like
   >  A displayer is found by checking registrations for the given class, its interfaces, and its superclasses and their interfaces.

   The next sentence about "most specific displayer" gets tricky.  Classes are fine, but I believe there are cases where you'd get an unambiguously "less specific" interface if the declaration hierarchy is weird.  Describing the behavior both simply and accurately is tricky.

**Comment by scottdraves** [comment]
ping

**Pull request merged**
